version: '3.8'
services:
  database:
    image: postgres
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel_docker
    volumes:
      - ./.docker/postgres/postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'


  php-apache:
    build:
      context: ./.docker/php
    ports:
        - '8091'
        
    volumes:
      - ./project:/var/www/laravel_docker
      - ./.docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database